name: Documentation Workflow

on:
  push:
    branches:
      - master

jobs:
  document:
    name: "Documentation"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements/docs.txt

      - name: Deploy Documentation
        run: |
          ls -ls
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin gh-pages
          mike deploy --push $(python setup.py --version) latest
