name: Verification Workflow

on:
  - push

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install tox

      - name: Verify, Test & Package
        run: tox

  codecov:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: verify
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install tox coverage

      - name: Execute coverage
        run: tox -e coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true